<?php
$z[0]=Array("global","",273,305);
$z[0][4]=array();
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("include","",372,407);
$z[1][4]=array();
$z[1][4]['filename']="left.htm";
$z[2]=Array("list","\n						<li>\n							<p class=\"news_time\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</p>\n						<h2>[field:title/]</h2>\n						<div class=\"news_cont\">\n							<p>[field:info/]</p>\n						</div>\n							<a href=\"[field:arcurl/]\" class=\"news_more\">查看更多</a>\n						</li>\n					",505,833);
$z[2][4]=array();
$z[2][4]['pagesize']="6";
$z[2][4]['type']="image.";
$z[3]=Array("pagelist","",901,972);
$z[3][4]=array();
$z[3][4]['listitem']="info,index,end,pre,next,pageno";
$z[3][4]['listsize']="6";

?>